### ISSUE TITLE
Simulate multiple vehicles traversing a network using SimPy

### ISSUE THREAD

**Issue by tk755** [CornellDataScience/Insights-Roadmaps#10]
Build a simulation framework using the graph structure in the `network` subpackage.
- `Vechicle` class that has a source node and a destination node - path can be retrieved from the get_path() method of the graph.
- `sim` module generates and runs all the `Vehicle` objects

**Comment by TusharK54** [comment]
Idea:
- `Vechicle` class that has a source node and a destination node - path can be retrieved from the `get_path()` method of the graph.
- `Manager` class that runs all the `Vehicle` objects and collects metadata of the simulation.

**Comment by ZiweiGu** [comment]
Completed
